version: '3.8'

services:
  ancient-luna-bot:
    image: ancient-luna-bot
    container_name: ancient-luna-bot
    restart: always
    environment:
      - TOKEN
      - COMMAND_PREFIX
      - DOTENV_CONFIG_QUIET
      - RES_API
      - WEBHOOK_ALLIANCE